/*
  Bell 429 Spare Parts — Cloudflare Worker security layer
  IMPORTANT:
  - Do NOT put passwords, API tokens, or Cloudflare secrets in index.html.
  - Set ADMIN_USERNAME and ADMIN_PASSWORD_HASH as secrets/vars outside source control.
  - This Worker is intentionally strict: unauthenticated admin API access is rejected.
*/

const SESSION_TTL_SECONDS = 60 * 60 * 8;
const MAX_BODY_BYTES = 64 * 1024;
const ALLOWED_ORIGIN = "https://REPLACE-WITH-YOUR-DOMAIN";

function json(data, status = 200, extra = {}) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      ...securityHeaders(),
      ...extra
    }
  });
}

function securityHeaders() {
  return {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
    "Content-Security-Policy":
      "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self';"
  };
}

function corsHeaders(origin) {
  if (!origin || origin !== ALLOWED_ORIGIN) return {};
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Allow-Headers": "content-type, x-csrf-token",
    "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
    "Vary": "Origin"
  };
}

function randomBytes(n) {
  return crypto.getRandomValues(new Uint8Array(n));
}

function b64url(bytes) {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

async function sha256(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return b64url(new Uint8Array(digest));
}

function parseCookies(request) {
  const out = {};
  const raw = request.headers.get("Cookie") || "";
  for (const part of raw.split(";")) {
    const i = part.indexOf("=");
    if (i > 0) out[part.slice(0, i).trim()] = part.slice(i + 1).trim();
  }
  return out;
}

function sameOrigin(request) {
  const origin = request.headers.get("Origin");
  return !origin || origin === ALLOWED_ORIGIN;
}

async function requireSession(request, env, csrfRequired = false) {
  if (!sameOrigin(request)) return { error: "origin" };

  const cookies = parseCookies(request);
  if (!cookies.b429_session) return { error: "auth" };

  const sidHash = await sha256(cookies.b429_session);
  const row = await env.DB.prepare(
    `SELECT s.id_hash, s.user_id, s.csrf_hash, s.expires_at, u.username, u.role
     FROM sessions s JOIN users u ON u.id=s.user_id
     WHERE s.id_hash=? AND s.expires_at>? AND u.enabled=1`
  ).bind(sidHash, Math.floor(Date.now() / 1000)).first();

  if (!row) return { error: "auth" };

  if (csrfRequired) {
    const token = request.headers.get("X-CSRF-Token") || "";
    if (!token || (await sha256(token)) !== row.csrf_hash) return { error: "csrf" };
  }

  return { user: row };
}

async function readJson(request) {
  const len = Number(request.headers.get("Content-Length") || 0);
  if (len > MAX_BODY_BYTES) throw new Error("body_too_large");
  const text = await request.text();
  if (new TextEncoder().encode(text).byteLength > MAX_BODY_BYTES) throw new Error("body_too_large");
  return JSON.parse(text);
}

function cookie(name, value, maxAge) {
  return `${name}=${value}; Max-Age=${maxAge}; Path=/; Secure; HttpOnly; SameSite=Strict`;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: { ...securityHeaders(), ...corsHeaders(request.headers.get("Origin")) }
      });
    }

    if (!sameOrigin(request)) return json({ error: "Forbidden origin" }, 403);

    // Health check
    if (url.pathname === "/api/health" && request.method === "GET") {
      return json({ ok: true });
    }

    // Login: credentials are checked server-side. Do not store the password in JS/localStorage.
    if (url.pathname === "/api/auth/login" && request.method === "POST") {
      try {
        const body = await readJson(request);
        const username = String(body.username || "").trim().slice(0, 120);
        const password = String(body.password || "");
        if (!username || !password) return json({ error: "Invalid credentials" }, 401);

        const user = await env.DB.prepare(
          "SELECT id, username, password_hash, role, enabled FROM users WHERE username=?"
        ).bind(username).first();

        // password_hash must be a PBKDF2 record generated by the provisioning script.
        if (!user || !user.enabled) return json({ error: "Invalid credentials" }, 401);

        const ok = await verifyPassword(password, user.password_hash);
        if (!ok) return json({ error: "Invalid credentials" }, 401);

        const sid = b64url(randomBytes(32));
        const csrf = b64url(randomBytes(32));
        const sidHash = await sha256(sid);
        const csrfHash = await sha256(csrf);
        const expires = Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS;

        await env.DB.prepare(
          "INSERT INTO sessions(id_hash,user_id,csrf_hash,expires_at) VALUES(?,?,?,?)"
        ).bind(sidHash, user.id, csrfHash, expires).run();

        return json(
          { ok: true, user: { username: user.username, role: user.role }, csrfToken: csrf },
          200,
          { "Set-Cookie": cookie("b429_session", sid, SESSION_TTL_SECONDS) }
        );
      } catch {
        return json({ error: "Bad request" }, 400);
      }
    }

    if (url.pathname === "/api/auth/logout" && request.method === "POST") {
      const cookies = parseCookies(request);
      if (cookies.b429_session) {
        await env.DB.prepare("DELETE FROM sessions WHERE id_hash=?")
          .bind(await sha256(cookies.b429_session)).run();
      }
      return json({ ok: true }, 200, {
        "Set-Cookie": cookie("b429_session", "", 0)
      });
    }

    // All order reads/writes require an authenticated session.
    if (url.pathname.startsWith("/api/orders")) {
      const write = ["POST", "PUT", "PATCH", "DELETE"].includes(request.method);
      const session = await requireSession(request, env, write);
      if (session.error === "auth") return json({ error: "Authentication required" }, 401);
      if (session.error === "csrf") return json({ error: "CSRF validation failed" }, 403);
      if (session.error === "origin") return json({ error: "Forbidden origin" }, 403);

      // Replace these statements with the exact order schema used by the existing UI.
      // The important security property is that the database is never trusted based
      // on a browser-supplied role or localStorage flag.
      if (request.method === "GET") {
        const rows = await env.DB.prepare(
          "SELECT * FROM orders ORDER BY created_at DESC LIMIT 500"
        ).all();
        return json(rows.results || []);
      }

      if (!["designer", "supervisor"].includes(session.user.role)) {
        return json({ error: "Forbidden" }, 403);
      }

      if (request.method === "DELETE") {
        const id = url.pathname.split("/").pop();
        if (!id || id === "orders") return json({ error: "Missing order id" }, 400);
        await env.DB.prepare("DELETE FROM orders WHERE id=?").bind(id).run();
        await env.DB.prepare(
          "INSERT INTO audit_log(user_id,action,target_id) VALUES(?,?,?)"
        ).bind(session.user.user_id, "delete_order", id).run();
        return json({ ok: true });
      }

      return json({ error: "Order write endpoint must be mapped to your existing schema" }, 501);
    }

    return new Response("Not found", {
      status: 404,
      headers: securityHeaders()
    });
  }
};

async function verifyPassword(password, record) {
  // Record format: pbkdf2$iterations$salt_b64url$hash_b64url
  const parts = String(record).split("$");
  if (parts.length !== 4 || parts[0] !== "pbkdf2") return false;
  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < 100000 || iterations > 1000000) return false;

  const salt = fromB64url(parts[2]);
  const expected = fromB64url(parts[3]);
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
    key,
    expected.length * 8
  );
  const actual = new Uint8Array(bits);
  if (actual.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < actual.length; i++) diff |= actual[i] ^ expected[i];
  return diff === 0;
}

function fromB64url(s) {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/") + pad);
  return Uint8Array.from(bin, c => c.charCodeAt(0));
}
